name: Auto approve

on: pull_request_target

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-approve:
    name: Auto approve Dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto approved Dependabot PR"
